"""
Django settings for music_controller project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()  # 加载环境变量 load the .env file
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-development-key-only')
# 从环境变量获取SECRET_KEY，如果不存在则使用开发环境的默认值

# SECURITY WARNING: don't run with debug turned on in production!
# 从环境变量读取配置，设置默认值用于开发环境
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() == 'true'

# config ALLOWED_HOSTS
ALLOWED_HOSTS_STR = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
if ALLOWED_HOSTS_STR:
    ALLOWED_HOSTS = ALLOWED_HOSTS_STR.split(',')
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Application definition
# settings.py

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # CORS support
    'api.apps.ApiConfig', # our app "api"
    'rest_framework', # another app we need
    'frontend.apps.FrontendConfig', # our frontend app
    'import_export',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware (must be first)
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'auto_garage_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'auto_garage_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

## 生产环境静态文件收集目录 collect static files in production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  

## 开发环境静态文件目录 the development static files directory
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'frontend/static'),
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework 配置 - 设置API认证和权限
# config REST_FRAMEWORK - set up API authentication and permissions
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',  # 使用Django session认证 use Django session authentication
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # 允许所有用户访问API allow any user to access
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour'
    }
}

# CSRF 配置 - 防止跨站请求伪造攻击
# config CSRF - prevent cross-site request forgery attacks
CSRF_COOKIE_NAME = 'csrftoken'  # CSRF token的cookie名称 the name of the CSRF token cookie
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'  # 前端发送CSRF token的header名称 the header name of the CSRF token sent by the frontend
CSRF_COOKIE_HTTPONLY = False  # 允许JavaScript访问Cookie allow JavaScript to access cookies
CSRF_COOKIE_SAMESITE = 'Lax'  # 跨域设置 cross-site setting
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# CORS 配置 - 允许前端跨域访问后端API
# config CORS - allow frontend to access backend APIs
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React开发服务器地址 React development server address
    "http://127.0.0.1:3000",  # 备用地址 backup address
]
# 重要：允许凭证（cookies）
# important: allow credentials
CORS_ALLOW_CREDENTIALS = True  # 允许跨域请求携带cookies和认证信息 allow cross-origin requests to carry cookies and authentication information

# Session 配置 - 管理用户会话
# config session - manage user sessions
SESSION_COOKIE_AGE = 86400  # session有效期24小时 session expiration time
SESSION_SAVE_EVERY_REQUEST = True  # 每次请求都更新session过期时间 update session expiration time on every request
SESSION_EXPIRE_AT_BROWSER_CLOSE = not DEBUG  ## 开发=False，生产=True, 关闭浏览器不清除session  clear session when the browser is closed


# 安全配置 - 基础安全防护
# config security - basic security measures
SECURE_HSTS_SECONDS = 31536000  # 1年, HSTS过期时间 HSTS expiration time
SECURE_BROWSER_XSS_FILTER = True  # 启用浏览器XSS过滤器 enable browser XSS filter
SECURE_CONTENT_TYPE_NOSNIFF = True  # 防止浏览器MIME类型嗅探 prevent MIME type sniffing in the browser

# 媒体文件位置 media file location
MEDIA_URL = '/media/' #path:http://127.0.0.1:8000/media
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 在文件末尾添加生产环境配置 append production configuration at the end
## 生产环境安全设置 production security settings
if not DEBUG:
    # 强制 HTTPS Force HTTPS
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Cookie 安全 Cookie security
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # HSTS 安全头 HSTS security header
    SECURE_HSTS_SECONDS = 31536000  # 1年
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # 其他安全头 Other security headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'